### ISSUE TITLE
3.0 Install and Run Warnings

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#40] opened 2020-09-28 05:13 UTC
**NOTE:** I am getting warnings to not download, then to not extract from the zip file stating that the file is from an unknown publisher and not to be trusted. It will install if you ignore the warnings, however. Every time I try to run Wink there is the message "Do you want to allow this app from an unknown publisher to make changes to your device?". Wink does run but there are all those warnings popping up.

**Comment by satishsampath** [comment] 2020-09-28 05:16
Is this different from what you saw with the beta build? I believe these warnings have always been there when installing Wink on windows 10?

**Comment by t-rains** [comment] 2020-09-28 05:38
Yes, they are the same as in beta. Just pointing that out since this is a public release.

**Comment by satishsampath** [comment] 2020-09-28 05:59
> Do you want to allow this app from an unknown publisher to make changes to your device?

Does this message come every time you install Wink, or every time you run after installing Wink?

**Comment by t-rains** [comment] 2020-09-28 19:43
That message occurs every time I run Wink.

**Comment by satishsampath** [comment] 2020-09-28 19:44
Ugh, that's unfortunate. Is there a checkbox/option to disable that warning
in the dialog that pops up?

**Comment by t-rains** [comment] 2020-09-28 19:55
There is only a system-wide User Account Control setting that is referenced. I have not found a setting for individual programs. 

From the Help site:

About User Account Control settings
Move the slider to select how much you want User Account Control to protect you from potentially harmful changes. Here's more info about each option:
Always notify will:
Notify you when programs try to install software or make changes to your computer.
Notify you when you make changes to Windows settings.
Freeze other tasks until you respond.
Note: This option is recommended if you routinely install new software or visit unfamiliar websites.
Notify me only when programs try to make changes to my computer
Notify you when programs try to install software or make changes to your computer.
Not notify you when you make changes to Windows settings.
Freeze other tasks until you respond.
Note: This option is recommended if you routinely install new software or visit unfamiliar websites, but you don't want to be notified when you make changes to Windows settings.
Notify me only when programs try to make changes to my computer (do not dim my desktop)
Notify you when programs try to install software or make changes to your computer.
Not notify you when you make changes to Windows settings.
Not freeze other tasks or wait for a response.
Note: This option is only recommended if it takes a long time to dim the desktop on your computer. Otherwise, it's recommended to choose one of the options above.
Never notify (Disable UAC) will:
Not notify you when programs try to install software or make changes to your computer.
Not notify you when you make changes to Windows settings.
Not freeze other tasks or wait for a response.
Note: This option isn't recommended due to security concerns.
If you need additional help, ask the Microsoft community.

Help from Microsoft

**Comment by satishsampath** [comment] 2020-09-28 20:00
Are you on Windows 10 as a standard user, Windows 10 as admin user or any
other OS?

**Comment by t-rains** [comment] 2020-09-28 20:03
I am on Windows 10 Home Edition 64 bit as Administrator.

**Comment by satishsampath** [comment] 2020-10-03 01:59
@t-rains , can you try to install the latest build from the website? It is signed with my certificate now and I verified on a Windows 10 Home 64-bit computer. I get a Chrome warning about 'this file is not usually downloaded' and MS SmartScreen Defender is also blocking it, but once you pass both it doesn't show any more warnings.

If you do see warning dialogs along the way, I'd appreciate posting screenshots of them in this issue.

**Comment by t-rains** [comment] 2020-10-03 21:14
Thanks for looking into that. I uninstalled the old Wink except for the personal wink files then installed from the website. The install went smoother with only Windows warning but I still get the “Do you want to allow this app from an unknown publisher ….” message (see attachment) which still occurs whenever I launch Wink.

**Comment by satishsampath** [comment] 2020-10-03 21:29
Sorry, no attachment came through. Can you visit this issue in the github website and attach your screenshot?

**Comment by t-rains** [comment] 2020-10-05 04:20
Sorry, here are the 3 dialogs that show. I  did a complete uninstall, virus scan, disc cleaning, and disc optimization, then restart before reinstalling Wink. The 'run dialog' is the one that continues to show up when I launch Wink. Oddly, 
![Install Dialog 1](https://user-images.githubusercontent.com/70729692/95039983-2bcae180-0687-11eb-8a64-d72ac4df914d.JPG)
![Install Dialog 2](https://user-images.githubusercontent.com/70729692/95039984-2c637800-0687-11eb-990f-7270f7e44e3d.JPG)
![Run Dialog](https://user-images.githubusercontent.com/70729692/95039985-2c637800-0687-11eb-9987-136d16f3b0de.JPG)


Windows recognizes your credentials until that dialog.

**Comment by satishsampath** [comment] 2020-10-05 05:59
Ok, I think the last dialog shows 'Publisher: unknown' because it's only the installer (winksetup.exe) that is signed with my certificate, not "wink.exe" . I can fix that, but before that I'd like to check why you are getting this dialog each time.

How are you starting Wink? Is it via a shortcut on desktop or start menu? By any chance, is the option "Run as administrator" enabled for that shortcut in the Properties dialog?

**Comment by t-rains** [comment] 2020-10-05 20:19
I have tried opening Wink from the Start Menu, taskbar, and desktop short cut, all with and without opening as administrator. All methods still open the same last dialog with the yellow heading reading "Do you want to allow this app from an unknown publisher ...".

**Comment by satishsampath** [comment] 2020-10-06 05:33
I sent you a custom build of Wink via Google Drive. Can you please confirm if you got it (it will be from my @debugmode.com mail id) and whether you are still seeing the warning dialog when you run Wink?

**Comment by t-rains** [comment] 2020-10-06 16:53
I installed the custom build of Wink you sent. The install went smoothly
![Custom Wink Start Screen](https://user-images.githubusercontent.com/70729692/95232674-b0b61800-07b9-11eb-8a4e-7f1a3ce8fa33.JPG)
 but I still get the start-up screen even running Wink as Administrator.

**Comment by satishsampath** [comment] 2020-10-09 05:27
I tried in a few different windows 10 machines that I have, couldn't reproduce. Hence closing this issue. If anyone else has this same issue, please reopen and also post a screenshot of your User Access Control setting in control panel.

**Closed by satishsampath** 2020-10-09 05:27 UTC

**Comment by t-rains** [comment] 2021-06-17 03:57
UPDATE: I have substantially updated my hardware, still using Windows 10 Home 64 bit, and no longer get any warnings or startup dialogs.
